services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - path: .env
        required: false
    volumes:
      - ./backend/data:/app/data

  frontend:
    image: nginx:alpine
    ports:
      - "5500:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
